
create table if not exists public.offers (
  id text primary key,
  source text not null,
  external_url text,
  title text not null,
  company text,
  location text,
  score integer not null,
  decision text not null,
  status text not null default 'new',
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

create index if not exists offers_status_idx on public.offers(status);
create index if not exists offers_decision_idx on public.offers(decision);

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  offer_id text not null references public.offers(id) on delete cascade,
  type text not null,
  message text not null,
  created_at timestamptz not null default now(),
  read boolean not null default false
);

alter table public.offers enable row level security;
alter table public.alerts enable row level security;

-- Frontend can read only. Writes are performed by GitHub Actions using service role.
create policy "public read offers" on public.offers for select using (true);
create policy "public read alerts" on public.alerts for select using (true);
